#!/usr/bin/env bash

# Function to parse yaml
# https://gist.github.com/epiloque/8cf512c6d64641bde388
# based on https://gist.github.com/pkuczynski/8665367
parse_yaml() {
    local prefix=$2
    local s
    local w
    local fs
    s='[[:blank:]]*'
    w='[a-zA-Z0-9_]*'
    fs="$(echo @|tr @ '\034')"
    sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s[:-]$s\(.*\)$s\$|\1$fs\2$fs\3|p" "$1" |
    awk -F"$fs" '{
    indent = length($1)/2;
    vname[indent] = $2;
    for (i in vname) {if (i > indent) {delete vname[i]}}
        if (length($3) > 0) {
            vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
            printf("%s%s%s=(\"%s\")\n", "'"$prefix"'",vn, $2, $3);
        }
    }' | sed 's/_=/+=/g'
}

[ ! -f "QuickBuildFile" ] && {
  echo "Error: Missing QuickBuildFile"
  exit 1
}

# parse_yaml QuickBuildFile "_"
eval $(parse_yaml QuickBuildFile "_")

export REPO_SLUG="${_slug}"

[ "${_build_configure}" = "meson" ] && {
  _dependencies_apt+=("python3-pip")
  _dependencies_apt+=("python3-setuptools")
  _dependencies_pip3+=("meson")
  _steps_build+=("meson _build")
}

[ "${_build_make}" = "ninja" ] && {
  _dependencies_apt+=("python3-pip")
  _dependencies_apt+=("python3-setuptools")
  _dependencies_pip3+=("ninja")
  _steps_compile+=("ninja -C _build")
  _steps_install+=("sudo ninja -C _build install")
}

wget -nv -c --show-progress --progress=bar:force:noscroll "${_dependencies_download[@]}"

[ ! "${_dependencies_apt}" = "" ] && {
  sudo apt install -y ${_dependencies_apt[@]}
}

[ ! "${_dependencies_pip3}" = "" ] && {
  sudo python3 -m pip install ${_dependencies_pip3[@]}
}


for package in "${_dependencies_quickdeploy[@]}"; do
  wget -nv -c --show-progress --progress=bar:force:noscroll "${package}" -O qdpkgf.tar.gz
  tar -xzf qdpkgf.tar.gz -C /
  rm qdpkgf.tar.gz
done

mkdir -p "build_environment"

for step in "${_steps_before[@]}"; do
  ${step}
done

for step in "${_steps_build[@]}"; do
  ${step}
done

for step in "${_steps_compile[@]}"; do
  ${step}
done

for step in "${_steps_install[@]}"; do
  ${step}
done

echo "---------------------------------------Start"

${_steps_install} | grep -v "subprojects" | grep ^"Installing" | awk '{print "cp -v --parents",$4"/$(basename "$2") ./build_environment"}' | sh 

echo "---------------------------------------End"

${_steps_install} 

for step in "${_steps_extra[@]}"; do
  ${step}
done

tar -cvzf ${_name}.tar.gz -C build_environment .

for step in "${_steps_after[@]}"; do
  ${step}
done






