name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Run builder script
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash quick-deploy
